version: '3.1'
services:
  excellent-erp:
    container_name: excellent-erp
    build:
      context: ./dockerfile
      dockerfile: odoo.Dockerfile
    volumes:
      - ./addons-extra:/mnt/addons-extra
      - ./odoo-config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    ports:
      - 8069:8069
    depends_on:
      - excellent-database
    restart: always
  
  excellent-database:
    container_name: excellent-database
    image: postgres:12
    volumes:
      - excellent-database-data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    #command: -p 5433
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

  pgadmin-stack:
    container_name: pgadmin-stack
    image: dpage/pgadmin4:5.4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:80
    links:
      - "excellent-database:pgsql-server"
    environment:
      PGADMIN_DEFAULT_EMAIL: shane@odootraining.ddns.net
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - excellent-database
    restart: always
    
  nginx-stack:
    container_name: nginx-stack
    build:
      context: ./dockerfile
      dockerfile: nginx.Dockerfile
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
    ports:
      - 80:80   #non secure
      - 443:443 #ssl
    depends_on:
      - excellent-erp
    restart: always

volumes:
  odoo-web-data:
  excellent-database-data:
  pgadmin-data: